### PR TITLE
Integrate Frontend Application

### PR DESCRIPTION
**Pull request by Brianktoo**

### CODE REVIEW

**Comment by MesfinGithinji** [comment]
Maxwell Kindly help me complete this review before we merge to develop

**Comment by maxwelbarno** [comment]
> @maxwelbarno Kindly help me complete this review before we merge to develop

Hello @MesfinGithinji
I am currently not feeling well but nonetheless I will review it ASAP

**Comment by maxwelbarno** [comment]
@Brianktoo
You guys forgot to pull the latest upstream changes before pushing your code and creating the PR.
Please pull the upstream changes first using `git pull origin develop`. 
There are a lot of conflicts.
CC @MesfinGithinji

**Comment by maxwelbarno** [comment]
@Brianktoo, @Simeonone and @MesfinGithinji 
As is, it is very difficult for me to clone the PR due to screaming conflicts. Please address this ASAP.

Otherwise great job to the Frontend team, we will build on this as our Dashboard Frontend

**Comment by maxwelbarno** [comment]
> @Brianktoo, @Simeonone and @MesfinGithinji As is, it is very difficult for me to clone the PR due to screaming conflicts. Please address this ASAP.
> 
> Otherwise great job to the Frontend team, we will build on this as our Dashboard Frontend

Screenshot from 2024-08-12 16-35-58

**Review by maxwelbarno — APPROVED** [review]
LGTM!

**Pull request merged**
